//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeTechie.RoundRobinScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SomeTechie.RoundRobinScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowdown {
            get {
                object obj = ResourceManager.GetObject("arrowdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowup {
            get {
                object obj = ResourceManager.GetObject("arrowup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save Copy Failed.
        /// </summary>
        internal static string AutoSaveCopyFailed {
            get {
                return ResourceManager.GetString("AutoSaveCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save Failed.
        /// </summary>
        internal static string AutoSaveFailed {
            get {
                return ResourceManager.GetString("AutoSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the error log?.
        /// </summary>
        internal static string ClearErrorLogMessage {
            get {
                return ResourceManager.GetString("ClearErrorLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Error Log?.
        /// </summary>
        internal static string ClearErrorLogTitle {
            get {
                return ResourceManager.GetString("ClearErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap confirm {
            get {
                object obj = ResourceManager.GetObject("confirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditScoreIcon {
            get {
                object obj = ResourceManager.GetObject("EditScoreIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error log was cleared successfully..
        /// </summary>
        internal static string ErrorLogClearedMessage {
            get {
                return ResourceManager.GetString("ErrorLogClearedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Log Cleared.
        /// </summary>
        internal static string ErrorLogClearedTitle {
            get {
                return ResourceManager.GetString("ErrorLogClearedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log could not be cleared..
        /// </summary>
        internal static string ErrorLogClearFailedMessage {
            get {
                return ResourceManager.GetString("ErrorLogClearFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Clear Error Log.
        /// </summary>
        internal static string ErrorLogClearFailedTitle {
            get {
                return ResourceManager.GetString("ErrorLogClearFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error log could not be saved..
        /// </summary>
        internal static string ErrorLogCopyFailedMessage {
            get {
                return ResourceManager.GetString("ErrorLogCopyFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Save Error Log.
        /// </summary>
        internal static string ErrorLogCopyFailedTitle {
            get {
                return ResourceManager.GetString("ErrorLogCopyFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shcedule failed to print..
        /// </summary>
        internal static string ErrorPrintingScheduleMessage {
            get {
                return ResourceManager.GetString("ErrorPrintingScheduleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Printing.
        /// </summary>
        internal static string ErrorPrintingScheduleTitle {
            get {
                return ResourceManager.GetString("ErrorPrintingScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to log:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorWritingToLogMessage {
            get {
                return ResourceManager.GetString("ErrorWritingToLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Write To Error Log.
        /// </summary>
        internal static string ErrorWritingToLogTitle {
            get {
                return ResourceManager.GetString("ErrorWritingToLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web interface could not be launched..
        /// </summary>
        internal static string LaunchWebInterfaceFailedMessage {
            get {
                return ResourceManager.GetString("LaunchWebInterfaceFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Launch Web Interface.
        /// </summary>
        internal static string LaunchWebInterfaceFailedTitle {
            get {
                return ResourceManager.GetString("LaunchWebInterfaceFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2011-2014 Some Techie
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:z
        ///
        ///The ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tournament Failed.
        /// </summary>
        internal static string NewTournamentFailed {
            get {
                return ResourceManager.GetString("NewTournamentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a new tournament..
        /// </summary>
        internal static string NewTournamentFailedMessage {
            get {
                return ResourceManager.GetString("NewTournamentFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error log has already been cleared or has not yet been created..
        /// </summary>
        internal static string NoErrorLogMessage {
            get {
                return ResourceManager.GetString("NoErrorLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error Log.
        /// </summary>
        internal static string NoErrorLogTitle {
            get {
                return ResourceManager.GetString("NoErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Static Proxy Files Failed.
        /// </summary>
        internal static string ProxyClearStaticFilesFailed {
            get {
                return ResourceManager.GetString("ProxyClearStaticFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Get Requests Failed.
        /// </summary>
        internal static string ProxyGetRequestsFailed {
            get {
                return ResourceManager.GetString("ProxyGetRequestsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Get Requests Failed (Could be because the listener was stopped).
        /// </summary>
        internal static string ProxyGetRequestsFailedPossibleThreadPause {
            get {
                return ResourceManager.GetString("ProxyGetRequestsFailedPossibleThreadPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Url.
        /// </summary>
        internal static string ProxyInvaildUrlTitle {
            get {
                return ResourceManager.GetString("ProxyInvaildUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Proxy Url &quot;{0}&quot;.
        /// </summary>
        internal static string ProxyInvalidUrl {
            get {
                return ResourceManager.GetString("ProxyInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Launch Proxied Interface.
        /// </summary>
        internal static string ProxyLaunchInterfaceFailed {
            get {
                return ResourceManager.GetString("ProxyLaunchInterfaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxied interface could not be launhed..
        /// </summary>
        internal static string ProxyLaunchInterfaceFailedMessage {
            get {
                return ResourceManager.GetString("ProxyLaunchInterfaceFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Request Failed {0}.
        /// </summary>
        internal static string ProxyProcessRequestsFailed {
            get {
                return ResourceManager.GetString("ProxyProcessRequestsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Reply Failed.
        /// </summary>
        internal static string ProxyReplyFailed {
            get {
                return ResourceManager.GetString("ProxyReplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set proxy url..
        /// </summary>
        internal static string ProxySetUrlFailed {
            get {
                return ResourceManager.GetString("ProxySetUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Proxy Url Failed.
        /// </summary>
        internal static string ProxySetUrlFailedTitle {
            get {
                return ResourceManager.GetString("ProxySetUrlFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start proxy..
        /// </summary>
        internal static string ProxyStartFailed {
            get {
                return ResourceManager.GetString("ProxyStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Proxy Failed.
        /// </summary>
        internal static string ProxyStartFailedTitle {
            get {
                return ResourceManager.GetString("ProxyStartFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not stop proxy..
        /// </summary>
        internal static string ProxyStopFailed {
            get {
                return ResourceManager.GetString("ProxyStopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Static Proxy File Failed &quot;{0}&quot;.
        /// </summary>
        internal static string ProxyUploadStaticFileFailed {
            get {
                return ResourceManager.GetString("ProxyUploadStaticFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap proxywaiting {
            get {
                object obj = ResourceManager.GetObject("proxywaiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes made to {0}?.
        /// </summary>
        internal static string SaveChangesMessage {
            get {
                return ResourceManager.GetString("SaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament failed to load. This may mean that the file has been corrupted..
        /// </summary>
        internal static string TournamentLoadFailedMessage {
            get {
                return ResourceManager.GetString("TournamentLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Load Tournament.
        /// </summary>
        internal static string TournamentLoadFailedTitle {
            get {
                return ResourceManager.GetString("TournamentLoadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament failed to save..
        /// </summary>
        internal static string TournamentSaveFailedMessage {
            get {
                return ResourceManager.GetString("TournamentSaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Save Tournament.
        /// </summary>
        internal static string TournamentSaveFailedTitle {
            get {
                return ResourceManager.GetString("TournamentSaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error has been added to the error log. The application will now exit:
        ///
        ///{0}.
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock?.
        /// </summary>
        internal static string UnlockTeams {
            get {
                return ResourceManager.GetString("UnlockTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding, removing, or moving teams after the tournament has started will cause the schedule to be regenerated, erasing all game scores.
        ///Are you sure you want to unlock?.
        /// </summary>
        internal static string UnlockTeamsMessage {
            get {
                return ResourceManager.GetString("UnlockTeamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the web server?
        ///This will disable web access and end any current connections..
        /// </summary>
        internal static string WebServerConfirmStopMessage {
            get {
                return ResourceManager.GetString("WebServerConfirmStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Web Server?.
        /// </summary>
        internal static string WebServerConfirmStopTitle {
            get {
                return ResourceManager.GetString("WebServerConfirmStopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Failed.
        /// </summary>
        internal static string WebServerListenFailed {
            get {
                return ResourceManager.GetString("WebServerListenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Failed (Could be because the thread or listener was stopped).
        /// </summary>
        internal static string WebServerListenFailedPossibleThreadPause {
            get {
                return ResourceManager.GetString("WebServerListenFailedPossibleThreadPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web server failed to {0}..
        /// </summary>
        internal static string WebServerOperationFailedMessage {
            get {
                return ResourceManager.GetString("WebServerOperationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not {0} Web Server.
        /// </summary>
        internal static string WebServerOperationFailedTitle {
            get {
                return ResourceManager.GetString("WebServerOperationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server Paused.
        /// </summary>
        internal static string WebServerPausedLogMessage {
            get {
                return ResourceManager.GetString("WebServerPausedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string WebServerRestart {
            get {
                return ResourceManager.GetString("WebServerRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server Resumed.
        /// </summary>
        internal static string WebServerResumedLogMessage {
            get {
                return ResourceManager.GetString("WebServerResumedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string WebServerStart {
            get {
                return ResourceManager.GetString("WebServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server Started.
        /// </summary>
        internal static string WebServerStartedLogMessage {
            get {
                return ResourceManager.GetString("WebServerStartedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server start failed once..
        /// </summary>
        internal static string WebServerStartFailed {
            get {
                return ResourceManager.GetString("WebServerStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting web server failed 5 times. Check the log for more details..
        /// </summary>
        internal static string WebServerStartFailed5Times {
            get {
                return ResourceManager.GetString("WebServerStartFailed5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string WebServerStop {
            get {
                return ResourceManager.GetString("WebServerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server Stopped.
        /// </summary>
        internal static string WebServerStoppedLogMessage {
            get {
                return ResourceManager.GetString("WebServerStoppedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinnerIcon {
            get {
                object obj = ResourceManager.GetObject("WinnerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
